### ISSUE TITLE
No datapoints

### ISSUE THREAD

**Issue by xhottam** [skydive-project/skydive-grafana-datasource#2]
openshift v3.3.0.35
kubernetes v1.3.0+52492b4

I can see my flows in skydive-analyzer

G.V().Has('Name', Regex('namespaces')).Out().Has("Type", "veth")

but in Grafana with last datasource version (same expresion) I'm unable to see data.

If I try with  Flows() (below)  I have a request error
	"G.At(1490780427,300).V().Has('Name', Regex('namespaces)).Out().Has(\"Type\", \"veth\").Flows().Metrics()"

if I try without Flows() . "No data points"

**Comment by safchain** [comment]
did you try to change the Skydive version in settings ?

**Comment by xhottam** [comment]
I'm running whith version >=0.10.x. If I try with version 0.9 I cannot fill up the expresion in query box I see {{ctrl.target.refId}}({ctrl.target.datasource}})

**Comment by safchain** [comment]
I just uploaded a new version in the dev branch. could you please test with this one ? 

In order to be sure that you gremlin expression is correct you can try it with the command line or using the Flows tab(top right) in the Skydive WebUI. 

I just did the test and I'm able to see Metrics for flows and interfaces.

**Comment by xhottam** [comment]
Currently I can fill expresion with verison 0.90 in the query filed but same thing "No datapoints."
The same query (plus .Flows() ) works as expected in flows tab in the Skydive WebUI. I tried with both datasources version.

**Comment by safchain** [comment]
So if you are using the Skydive docker image without any tag you should be able to use this datasource with the 0.10x version.

could you try to do a timed request with the Flows tab to be sure that the datastore is working properly.

something like:

G.At("-5s", 500).V().....

or even better opening the javascript console you should be able to get the gremlin request made by Grafana. So that you could copy/paste it in the Flows tab

**Comment by xhottam** [comment]
Iim using Skydive (https://github.com/skydive-project/skydive/tree/master/contrib/openshift) i n OCP cluster
openshift v3.3.0.35
kubernetes v1.3.0+52492b4

query : G.V().Has('Name', Regex('namespaces')).Out().Has("Type", "veth")

js console output  : G.At(1490788807).V().Has('Name', Regex('globalpaas-infrastructure')).Out().Has("Type", "veth").Metrics()

js console output in Skydive WebUI
Invalid step 'Limit' on '*traversal.MetricsTraversalStep'Query was : G.V().Has('Name', Regex('namespaces')).Out().Has("Type", "veth").Metrics().Limit(30)

**Comment by safchain** [comment]
Closing this one as the last commits should fix the issue, will re-open if needed
